# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/verilog_src/MY_Basys-3-Master.xdc

# Block Designs: bd/AXI4_LITE_I2C_PERIPH/AXI4_LITE_I2C_PERIPH.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI4_LITE_I2C_PERIPH || ORIG_REF_NAME==AXI4_LITE_I2C_PERIPH} -quiet] -quiet

# IP: bd/AXI4_LITE_I2C_PERIPH/ip/AXI4_LITE_I2C_PERIPH_microblaze_0_0/AXI4_LITE_I2C_PERIPH_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI4_LITE_I2C_PERIPH_microblaze_0_0 || ORIG_REF_NAME==AXI4_LITE_I2C_PERIPH_microblaze_0_0} -quiet] -quiet

# IP: bd/AXI4_LITE_I2C_PERIPH/ip/AXI4_LITE_I2C_PERIPH_dlmb_v10_0/AXI4_LITE_I2C_PERIPH_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI4_LITE_I2C_PERIPH_dlmb_v10_0 || ORIG_REF_NAME==AXI4_LITE_I2C_PERIPH_dlmb_v10_0} -quiet] -quiet

# IP: bd/AXI4_LITE_I2C_PERIPH/ip/AXI4_LITE_I2C_PERIPH_ilmb_v10_0/AXI4_LITE_I2C_PERIPH_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI4_LITE_I2C_PERIPH_ilmb_v10_0 || ORIG_REF_NAME==AXI4_LITE_I2C_PERIPH_ilmb_v10_0} -quiet] -quiet

# IP: bd/AXI4_LITE_I2C_PERIPH/ip/AXI4_LITE_I2C_PERIPH_dlmb_bram_if_cntlr_0/AXI4_LITE_I2C_PERIPH_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI4_LITE_I2C_PERIPH_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==AXI4_LITE_I2C_PERIPH_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/AXI4_LITE_I2C_PERIPH/ip/AXI4_LITE_I2C_PERIPH_ilmb_bram_if_cntlr_0/AXI4_LITE_I2C_PERIPH_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI4_LITE_I2C_PERIPH_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==AXI4_LITE_I2C_PERIPH_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/AXI4_LITE_I2C_PERIPH/ip/AXI4_LITE_I2C_PERIPH_lmb_bram_0/AXI4_LITE_I2C_PERIPH_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI4_LITE_I2C_PERIPH_lmb_bram_0 || ORIG_REF_NAME==AXI4_LITE_I2C_PERIPH_lmb_bram_0} -quiet] -quiet

# IP: bd/AXI4_LITE_I2C_PERIPH/ip/AXI4_LITE_I2C_PERIPH_mdm_1_0/AXI4_LITE_I2C_PERIPH_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI4_LITE_I2C_PERIPH_mdm_1_0 || ORIG_REF_NAME==AXI4_LITE_I2C_PERIPH_mdm_1_0} -quiet] -quiet

# IP: bd/AXI4_LITE_I2C_PERIPH/ip/AXI4_LITE_I2C_PERIPH_clk_wiz_1_0/AXI4_LITE_I2C_PERIPH_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI4_LITE_I2C_PERIPH_clk_wiz_1_0 || ORIG_REF_NAME==AXI4_LITE_I2C_PERIPH_clk_wiz_1_0} -quiet] -quiet

# IP: bd/AXI4_LITE_I2C_PERIPH/ip/AXI4_LITE_I2C_PERIPH_rst_clk_wiz_1_100M_0/AXI4_LITE_I2C_PERIPH_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI4_LITE_I2C_PERIPH_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==AXI4_LITE_I2C_PERIPH_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/AXI4_LITE_I2C_PERIPH/ip/AXI4_LITE_I2C_PERIPH_axi_uartlite_0_0/AXI4_LITE_I2C_PERIPH_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI4_LITE_I2C_PERIPH_axi_uartlite_0_0 || ORIG_REF_NAME==AXI4_LITE_I2C_PERIPH_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/AXI4_LITE_I2C_PERIPH/ip/AXI4_LITE_I2C_PERIPH_xbar_0/AXI4_LITE_I2C_PERIPH_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI4_LITE_I2C_PERIPH_xbar_0 || ORIG_REF_NAME==AXI4_LITE_I2C_PERIPH_xbar_0} -quiet] -quiet

# IP: bd/AXI4_LITE_I2C_PERIPH/ip/AXI4_LITE_I2C_PERIPH_microblaze_0_axi_periph_0/AXI4_LITE_I2C_PERIPH_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI4_LITE_I2C_PERIPH_microblaze_0_axi_periph_0 || ORIG_REF_NAME==AXI4_LITE_I2C_PERIPH_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/AXI4_LITE_I2C_PERIPH/ip/AXI4_LITE_I2C_PERIPH_axi_gpio_0_0/AXI4_LITE_I2C_PERIPH_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI4_LITE_I2C_PERIPH_axi_gpio_0_0 || ORIG_REF_NAME==AXI4_LITE_I2C_PERIPH_axi_gpio_0_0} -quiet] -quiet

# IP: bd/AXI4_LITE_I2C_PERIPH/ip/AXI4_LITE_I2C_PERIPH_AXI4_LITE_I2C_PERIPH_0_0/AXI4_LITE_I2C_PERIPH_AXI4_LITE_I2C_PERIPH_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI4_LITE_I2C_PERIPH_AXI4_LITE_I2C_PERIPH_0_0 || ORIG_REF_NAME==AXI4_LITE_I2C_PERIPH_AXI4_LITE_I2C_PERIPH_0_0} -quiet] -quiet

# IP: bd/AXI4_LITE_I2C_PERIPH/ip/AXI4_LITE_I2C_PERIPH_axi4_lite_spi_master_0_0/AXI4_LITE_I2C_PERIPH_axi4_lite_spi_master_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI4_LITE_I2C_PERIPH_axi4_lite_spi_master_0_0 || ORIG_REF_NAME==AXI4_LITE_I2C_PERIPH_axi4_lite_spi_master_0_0} -quiet] -quiet

# XDC: c:/fpga_harman/250522_I2C_MASTER_MICROBLAZE/250522_I2C_MASTER_MICROBLAZE.gen/sources_1/bd/AXI4_LITE_I2C_PERIPH/ip/AXI4_LITE_I2C_PERIPH_microblaze_0_0/AXI4_LITE_I2C_PERIPH_microblaze_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==AXI4_LITE_I2C_PERIPH_microblaze_0_0 || ORIG_REF_NAME==AXI4_LITE_I2C_PERIPH_microblaze_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/fpga_harman/250522_I2C_MASTER_MICROBLAZE/250522_I2C_MASTER_MICROBLAZE.gen/sources_1/bd/AXI4_LITE_I2C_PERIPH/ip/AXI4_LITE_I2C_PERIPH_microblaze_0_0/AXI4_LITE_I2C_PERIPH_microblaze_0_0_ooc_debug.xdc

# XDC: c:/fpga_harman/250522_I2C_MASTER_MICROBLAZE/250522_I2C_MASTER_MICROBLAZE.gen/sources_1/bd/AXI4_LITE_I2C_PERIPH/ip/AXI4_LITE_I2C_PERIPH_dlmb_v10_0/AXI4_LITE_I2C_PERIPH_dlmb_v10_0_ooc.xdc

# XDC: c:/fpga_harman/250522_I2C_MASTER_MICROBLAZE/250522_I2C_MASTER_MICROBLAZE.gen/sources_1/bd/AXI4_LITE_I2C_PERIPH/ip/AXI4_LITE_I2C_PERIPH_ilmb_v10_0/AXI4_LITE_I2C_PERIPH_ilmb_v10_0_ooc.xdc

# XDC: c:/fpga_harman/250522_I2C_MASTER_MICROBLAZE/250522_I2C_MASTER_MICROBLAZE.gen/sources_1/bd/AXI4_LITE_I2C_PERIPH/ip/AXI4_LITE_I2C_PERIPH_dlmb_bram_if_cntlr_0/AXI4_LITE_I2C_PERIPH_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: c:/fpga_harman/250522_I2C_MASTER_MICROBLAZE/250522_I2C_MASTER_MICROBLAZE.gen/sources_1/bd/AXI4_LITE_I2C_PERIPH/ip/AXI4_LITE_I2C_PERIPH_ilmb_bram_if_cntlr_0/AXI4_LITE_I2C_PERIPH_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: c:/fpga_harman/250522_I2C_MASTER_MICROBLAZE/250522_I2C_MASTER_MICROBLAZE.gen/sources_1/bd/AXI4_LITE_I2C_PERIPH/ip/AXI4_LITE_I2C_PERIPH_lmb_bram_0/AXI4_LITE_I2C_PERIPH_lmb_bram_0_ooc.xdc

# XDC: c:/fpga_harman/250522_I2C_MASTER_MICROBLAZE/250522_I2C_MASTER_MICROBLAZE.gen/sources_1/bd/AXI4_LITE_I2C_PERIPH/ip/AXI4_LITE_I2C_PERIPH_mdm_1_0/AXI4_LITE_I2C_PERIPH_mdm_1_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==AXI4_LITE_I2C_PERIPH_mdm_1_0 || ORIG_REF_NAME==AXI4_LITE_I2C_PERIPH_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/fpga_harman/250522_I2C_MASTER_MICROBLAZE/250522_I2C_MASTER_MICROBLAZE.gen/sources_1/bd/AXI4_LITE_I2C_PERIPH/ip/AXI4_LITE_I2C_PERIPH_mdm_1_0/AXI4_LITE_I2C_PERIPH_mdm_1_0_ooc_trace.xdc

# XDC: c:/fpga_harman/250522_I2C_MASTER_MICROBLAZE/250522_I2C_MASTER_MICROBLAZE.gen/sources_1/bd/AXI4_LITE_I2C_PERIPH/ip/AXI4_LITE_I2C_PERIPH_clk_wiz_1_0/AXI4_LITE_I2C_PERIPH_clk_wiz_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==AXI4_LITE_I2C_PERIPH_clk_wiz_1_0 || ORIG_REF_NAME==AXI4_LITE_I2C_PERIPH_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/fpga_harman/250522_I2C_MASTER_MICROBLAZE/250522_I2C_MASTER_MICROBLAZE.gen/sources_1/bd/AXI4_LITE_I2C_PERIPH/ip/AXI4_LITE_I2C_PERIPH_clk_wiz_1_0/AXI4_LITE_I2C_PERIPH_clk_wiz_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==AXI4_LITE_I2C_PERIPH_clk_wiz_1_0 || ORIG_REF_NAME==AXI4_LITE_I2C_PERIPH_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/fpga_harman/250522_I2C_MASTER_MICROBLAZE/250522_I2C_MASTER_MICROBLAZE.gen/sources_1/bd/AXI4_LITE_I2C_PERIPH/ip/AXI4_LITE_I2C_PERIPH_clk_wiz_1_0/AXI4_LITE_I2C_PERIPH_clk_wiz_1_0_ooc.xdc

# XDC: c:/fpga_harman/250522_I2C_MASTER_MICROBLAZE/250522_I2C_MASTER_MICROBLAZE.gen/sources_1/bd/AXI4_LITE_I2C_PERIPH/ip/AXI4_LITE_I2C_PERIPH_rst_clk_wiz_1_100M_0/AXI4_LITE_I2C_PERIPH_rst_clk_wiz_1_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==AXI4_LITE_I2C_PERIPH_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==AXI4_LITE_I2C_PERIPH_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/fpga_harman/250522_I2C_MASTER_MICROBLAZE/250522_I2C_MASTER_MICROBLAZE.gen/sources_1/bd/AXI4_LITE_I2C_PERIPH/ip/AXI4_LITE_I2C_PERIPH_rst_clk_wiz_1_100M_0/AXI4_LITE_I2C_PERIPH_rst_clk_wiz_1_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==AXI4_LITE_I2C_PERIPH_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==AXI4_LITE_I2C_PERIPH_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/fpga_harman/250522_I2C_MASTER_MICROBLAZE/250522_I2C_MASTER_MICROBLAZE.gen/sources_1/bd/AXI4_LITE_I2C_PERIPH/ip/AXI4_LITE_I2C_PERIPH_axi_uartlite_0_0/AXI4_LITE_I2C_PERIPH_axi_uartlite_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==AXI4_LITE_I2C_PERIPH_axi_uartlite_0_0 || ORIG_REF_NAME==AXI4_LITE_I2C_PERIPH_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/fpga_harman/250522_I2C_MASTER_MICROBLAZE/250522_I2C_MASTER_MICROBLAZE.gen/sources_1/bd/AXI4_LITE_I2C_PERIPH/ip/AXI4_LITE_I2C_PERIPH_axi_uartlite_0_0/AXI4_LITE_I2C_PERIPH_axi_uartlite_0_0_ooc.xdc

# XDC: c:/fpga_harman/250522_I2C_MASTER_MICROBLAZE/250522_I2C_MASTER_MICROBLAZE.gen/sources_1/bd/AXI4_LITE_I2C_PERIPH/ip/AXI4_LITE_I2C_PERIPH_axi_uartlite_0_0/AXI4_LITE_I2C_PERIPH_axi_uartlite_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==AXI4_LITE_I2C_PERIPH_axi_uartlite_0_0 || ORIG_REF_NAME==AXI4_LITE_I2C_PERIPH_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/fpga_harman/250522_I2C_MASTER_MICROBLAZE/250522_I2C_MASTER_MICROBLAZE.gen/sources_1/bd/AXI4_LITE_I2C_PERIPH/ip/AXI4_LITE_I2C_PERIPH_xbar_0/AXI4_LITE_I2C_PERIPH_xbar_0_ooc.xdc

# XDC: c:/fpga_harman/250522_I2C_MASTER_MICROBLAZE/250522_I2C_MASTER_MICROBLAZE.gen/sources_1/bd/AXI4_LITE_I2C_PERIPH/ip/AXI4_LITE_I2C_PERIPH_axi_gpio_0_0/AXI4_LITE_I2C_PERIPH_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==AXI4_LITE_I2C_PERIPH_axi_gpio_0_0 || ORIG_REF_NAME==AXI4_LITE_I2C_PERIPH_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/fpga_harman/250522_I2C_MASTER_MICROBLAZE/250522_I2C_MASTER_MICROBLAZE.gen/sources_1/bd/AXI4_LITE_I2C_PERIPH/ip/AXI4_LITE_I2C_PERIPH_axi_gpio_0_0/AXI4_LITE_I2C_PERIPH_axi_gpio_0_0_ooc.xdc

# XDC: c:/fpga_harman/250522_I2C_MASTER_MICROBLAZE/250522_I2C_MASTER_MICROBLAZE.gen/sources_1/bd/AXI4_LITE_I2C_PERIPH/ip/AXI4_LITE_I2C_PERIPH_axi_gpio_0_0/AXI4_LITE_I2C_PERIPH_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==AXI4_LITE_I2C_PERIPH_axi_gpio_0_0 || ORIG_REF_NAME==AXI4_LITE_I2C_PERIPH_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/fpga_harman/250522_I2C_MASTER_MICROBLAZE/250522_I2C_MASTER_MICROBLAZE.gen/sources_1/bd/AXI4_LITE_I2C_PERIPH/AXI4_LITE_I2C_PERIPH_ooc.xdc
